# Generated by Django 3.1.7 on 2021-03-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChgRecord',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('lineId', models.CharField(default='Q000', max_length=10)),
                ('deviceName', models.CharField(max_length=120)),
                ('loopNo', models.CharField(max_length=50)),
                ('opeContent', models.CharField(max_length=256)),
                ('opeReason', models.CharField(max_length=256)),
                ('opeDate', models.DateField()),
                ('adjValueBefore', models.FloatField(default=0.0)),
                ('adjValueAfter', models.FloatField(default=0.0)),
                ('adjValueUnit', models.CharField(max_length=10)),
            ],
        ),
    ]
